basePath: /api/v1
definitions:
  rest.Attendant:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  rest.CreateAttendantRequest:
    properties:
      name:
        type: string
    type: object
  rest.HTTPResponse:
    properties:
      msg:
        example: any message
        type: string
    type: object
  rest.IDResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact:
    email: contato@coding4u.com.br
    name: Coding4u
  description: Swagger API for Attendant Service.
  termsOfService: http://swagger.io/terms/
  title: Attendant Swagger API
  version: "1.0"
paths:
  /attendants:
    post:
      consumes:
      - application/json
      description: Router for create a new attendant
      operationId: createAttendant
      parameters:
      - description: JSON body for create a new attendant
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.CreateAttendantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.IDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.HTTPResponse'
      summary: create a new attendant
      tags:
      - Attendant
  /attendants/{attendant_id}:
    get:
      consumes:
      - application/json
      description: Router for find a attendant
      operationId: findAttendant
      parameters:
      - description: Attendant ID
        in: path
        name: attendant_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Attendant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.HTTPResponse'
      summary: find a attendant
      tags:
      - Attendant
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
