apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-v1
  labels:
    app: employee
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
      version: v1
  template:
    metadata:
      labels:
        app: employee
        version: v1
    spec:
      containers:
        - name: employee
          image: ghcr.io/c-4u/pinned-employee
          imagePullPolicy: IfNotPresent
          ports:
            - name: rest
              containerPort: 8080
          envFrom:
            - secretRef:
                name: employee-secret
          resources:
            limits:
              memory: '128Mi'
              cpu: '50m'

      imagePullSecrets:
        - name: regsecret
