apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
    service: employee
spec:
  type: ClusterIP
  selector:
    app: employee
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
